export const IS_LOADING = "IS_LOADING"
export const IS_ERROR = "IS_ERROR"

export const GET_SURVEYS = "GET_SURVEYS"
export const GET_SURVEYS_LOADING = "GET_SURVEYS_LOADING"
export const GET_SURVEYS_ERROR = "GET_SURVEYS_ERROR"

export const GET_QUESTION_BY_ID = "GET_QUESTION_BY_ID"
export const GET_QUESTION_BY_ID_LOADING = "GET_QUESTION_BY_ID_LOADING"
export const GET_QUESTION_BY_ID_ERROR = "GET_QUESTION_BY_ID_ERROR"

export const GET_QUESTIONS_BY_SURVEY_ID = "GET_QUESTIONS_BY_SURVEY_ID"
export const GET_QUESTIONS_BY_SURVEY_ID_LOADING = "GET_QUESTIONS_BY_SURVEY_ID_LOADING"
export const GET_QUESTIONS_BY_SURVEY_ID_ERROR = "GET_QUESTIONS_BY_SURVEY_ID_ERROR"

export const SAVE_QUESTION = "SAVE_QUESTION"
export const SAVE_QUESTION_LOADING = "SAVE_QUESTION_LOADING"
export const SAVE_QUESTION_ERROR = "SAVE_QUESTION_ERROR"

export const SAVE_ANSWER = "SAVE_ANSWER"
export const SAVE_ANSWER_LOADING = "SAVE_ANSWER_LOADING"
export const SAVE_ANSWER_ERROR = "SAVE_ANSWER_ERROR"

export const QUESTION_CONTROL_TYPE = "QUESTION_CONTROL_TYPE"
export const QUESTION_CONTROL_TYPE_LOADING = "QUESTION_CONTROL_TYPE_LOADING"
export const QUESTION_CONTROL_TYPE_ERROR = "QUESTION_CONTROL_TYPE_ERROR"

export const SEARCHRX_DRUG = "SEARCHRX_DRUG"
export const SEARCHRX_DRUG_LOADING = "SEARCHRX_DRUG_LOADING"
export const SEARCHRX_DRUG_ERROR = "SEARCHRX_DRUG_ERROR"

export const SEARCH_PCP = "SEARCH_PCP"
export const SEARCH_PCP_LOADING = "SEARCH_PCP_LOADING"
export const SEARCH_PCP_ERROR = "SEARCH_PCP_ERROR"

export const GET_PLANS = "GET_PLANS"
export const GET_PLANS_LOADING = "GET_PLANS_LOADING"
export const GET_PLANS_ERROR = "GET_PLANS_ERROR"

export const GET_PLANS_BY_PLAN_ID_LOADING = "GET_PLANS_BY_PLAN_ID_LOADING"
export const GET_PLANS_DETAILS = "GET_PLANS_DETAILS"
export const GET_PLAN_BY_PLAN_ID_ERROR = "GET_PLAN_BY_PLAN_ID_ERROR"
 
export const POST_REGISTER_LOADING = "POST_REGISTER_LOADING"
export const POST_REGISTER = "POST_REGISTER"
export const POST_REGISTER_ERROR = "POST_REGISTER_ERROR"

export const SAVE_AUTHDATA_LOADING = "SAVE_AUTHDATA_LOADING"
export const SAVE_AUTHDATA = "SAVE_AUTHDATA"
export const SAVE_AUTHENTDATA_ERROR = "SAVE_AUTHENTDATA_ERROR"

export const SAVE_INQUERY = "SAVE_INQUERY"
export const SAVE_INQUERY_LOADING = "SAVE_INQUERY_LOADING"
export const SAVE_INQUERY_ERROR = "SAVE_INQUERY_ERROR"

export const GET_INQUERY_HISTORY = "GET_INQUERY_HISTORY"
export const GET_INQUERY_HISTORY_LOADING = "GET_INQUERY_HISTORY_LOADING"
export const GET_INQUERY_HISTORY_ERROR = "GET_INQUERY_HISTORY_ERROR"

export const GET_QUESTIONS_BY_SURVEY_ID_ORDER_NO = "GET_QUESTIONS_BY_SURVEY_ID_ORDER_NO"
export const GET_QUESTIONS_BY_SURVEY_ORDER_NO_ID_LOADING = "GET_QUESTIONS_BY_SURVEY_ORDER_NO_ID_LOADING"
export const GET_QUESTIONS_BY_SURVEY_ID_ORDER_NO_ERROR = "GET_QUESTIONS_BY_SURVEY_ID_ORDER_NO_ERROR"

export const ELIGIBLECHECK = "ELIGIBLECHECK"
export const ELIGIBLECHECK_LOADING = "ELIGIBLECHECK_LOADING"
export const ELIGIBLECHECK_ERROR = "ELIGIBLECHECK_ERROR"

export const GET_ZIPCODE = "GET_ZIPCODE"
export const GET_ZIPCODE_LOADING = "GET_ZIPCODE_LOADING"
export const GET_ZIPCODE_ERROR = "GET_ZIPCODE_ERROR"
 
export const PROFILE_LOADING = "PROFILE_LOADING"
export const PROFILE = "PROFILE"
export const PROFILE_ERROR = "PROFILE_ERROR"

export const GET_INQUERY_BY_ID = "GET_INQUERY__BY_ID"
export const GET_INQUERY__BY_ID_LOADING = "GET_INQUERY__BY_ID_LOADING"
export const GET_INQUERY__BY_ID_ERROR = "GET_INQUERY__BY_ID_ERROR"

export const SEARCH_PHARMACIES = "SEARCH_PHARMACIES"
export const SEARCH_PHARMACIES_LOADING = "SEARCH_PHARMACIES_LOADING"
export const SEARCH_PHARMACIES_ERROR = "SEARCH_PHARMACIES_ERROR"

export const SAVE_CONTACT_US = "SAVE_CONTACT_US"
export const SAVE_CONTACT_US_LOADING = "SAVE_CONTACT_US_LOADING"
export const SAVE_CONTACT_US_ERROR = "SAVE_CONTACT_US_ERROR"