export const endPoints = {
    getSurveys : 'qna/surveys',
    getQuestionById : 'qna/question',
    getQuestionBySurveyId : 'qna/questions',
    saveQuestion : 'qna/savequestion',
    saveAnswer : 'qna/saveanswer',
    questionControlTypes : 'qna/questioncontroltypes',
    searchrxdrug : 'planmanager/searchrxdrug',
    searchpcp : 'planmanager/searchpcp',
    searchpharmacies : 'planmanager/searchpharmacies',
    getifpquote : 'planmanager/getifpquote',
    register: "account/register",
    authenticate: "account/authenticate",
    saveInquery : 'inquiry/savepotentiallead',
    getQuestionBySurveyIdAndOrderNo : 'qna/nextorderquestion',
    eligiblecheck: "planmanager/eligiblecheck",
    getzipcodeinfo : 'planmanager/getzipcodeinfo',
    getuserbyid : 'account/getuserbyid',
    getinquiriesbyuser : 'inquiry/getinquiriesbyuser',
    getinquiriebyid : 'inquiry/getpotentialleads',
    saveContact : 'Notification/sendcontactusemail',
}